version: "2.4"
services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data
      # - ./api/migrations/scripts:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: blogs-db
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: topsecret
    healthcheck:
      test: nc -z localhost 5432 || exit -1
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

  api:
    image: acme/api:1.0
    build: api
    ports:
      - 5000:5000
    volumes:
      - ./api:/app
    command: dotnet watch run
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg-data: